---

#--------- deploy VMs

- hosts: vmware
  gather_facts: false
  vars_files:
    - gvar.yml
  roles:
     - deploy-vm
  
  tasks:     
  - name: Wait  for port 22 to become open 
    wait_for:
      port: 22
      host: '{{ guest_custom_ip }}'
      delay: 10
    connection: local

 #------- perpare nodes network
- hosts: network
  gather_facts: false
  tasks:
  - name: copy script to local host
    copy: 
      src: /home/labtest/aci-kube/config-net.py 
      dest: /home/labtest/config-net.py
  - name: copy template  
    copy: 
      src: /home/labtest/aci-kube/interface-template.yml 
      dest: /home/labtest/interface-template.yml


  - name: run py script
    command: /usr/bin/python3 /home/labtest/config-net.py {{ ip }} {{ node }} {{ vlan }} 10 
    register: output
  - set_fact:
          mackey: output.stdout[1:-1] 
  - debug: 
        var: output.stdout

  - name: modify dhcp.conf
    lineinfile:
         backup: no
         backrefs: yes
         state: present
         path: '/etc/dhcp/dhclient.conf'
         regexp: '^(\s*)[#]?{{ item.search }}(: )*'
         line: '\1{{ item.replace }}'
    with_items:
         - { search: 'send dhcp-client-identifier', replace: 'send dhcp-client-identifier 01:{{ output.stdout }}' }  
  - name: restart network
    shell: |
            rm -f /etc/netplan/*vmware*
            cp /home/labtest/interface-template.yml  /etc/netplan/00-installer-config.yaml 
            netplan apply

  - name: Wait  for port 22 to become open
    wait_for:
      port: 22
      delay: 10
    connection: local


- hosts: node
  gather_facts: false
  vars_files:
    - gvar.yml
  roles:
     - config-worker

  environment:
    no_proxy: 10.81.0.10,10.82.0.1,10.86.0.1,localhost
    http_proxy: http://proxy.esl.cisco.com:80
    https_proxy: http://proxy.esl.cisco.com:80
  handlers:
    - name: docker status
      service: name=docker state=started
