- name: Deploy VM from template
  vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    validate_certs: no
    datacenter: '{{ deploy_vsphere_datacenter }}'
    #cluster: '{{ deploy_vsphere_cluster }}'
    #resource_pool: '{{ deploy_vsphere_resourcepool }}'
    folder: '{{ deploy_vsphere_folder }}'
    name: '{{ inventory_hostname }}'
    state: poweredon
    guest_id: '{{ guest_id }}'
    #annotation: "{{ guest_notes }}"
    #disk:
    # datastore: '{{ deploy_vsphere_datastore }}'
    networks:
    - name: '{{ guest_network }}'
      ip: '{{ guest_custom_ip }}'
      netmask: '{{ guest_netmask }}'
      gateway: '{{ guest_gateway }}'
      device_type: vmxnet3
      start_connected: true
      state: new
      connected: True
    - name: '{{ guest_network_2 }}'
      device_type: vmxnet3
      start_connected: true
      state: new
      connected: True

      dns_servers:
       - '{{ guest_dns_server }}'
           
    customization:
         # domain : '{{ guest_domain_name }}'
      hostname: '{{ inventory_hostname }}'
    template: '{{ guest_template }}'
    wait_for_ip_address: yes
    state: poweredon
      
    # loop: "{{ groups['vmware']}}"
    # async: 60
    #poll: 30
  delegate_to: localhost
- name: pause
  pause: seconds=30
