- name: Deploy VM from template
  vmware_guest:
    hostname: '{{ vcenter_ip }}'
    username: '{{ vcenter_user }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter: '{{ deploy_datacenter }}'
    folder: '{{ deploy_vsphere_folder }}'
    name: '{{ inventory_hostname }}'
    state: poweredon
    guest_id: '{{ guest_id }}'
   
    networks:
    - name: '{{ guest_network }}'
      ip: '{{ guest_custom_ip }}'
      netmask: '{{ guest_netmask }}'
      gateway: '{{ guest_gateway }}'
      device_type: vmxnet3
      start_connected: true
      state: new
      connected: True
    - name: '{{ guest_network_2 }}'
      device_type: vmxnet3
      start_connected: true
      state: new
      connected: True

      dns_servers:
       - '{{ guest_dns_server }}'
           
    customization:
  
      hostname: '{{ inventory_hostname }}'
    template: '{{ guest_template }}'
    wait_for_ip_address: yes
    state: poweredon
  
  delegate_to: localhost
- name: pause
  pause: seconds=15
